"""Autonomy acceptance uses synthetic approved rules, never medical thresholds."""
from datetime import date, timedelta
from uuid import uuid4
from dataclasses import replace
import pytest
from sqlalchemy import create_engine, select, func
from sqlalchemy.orm import Session
from executive_health_ai.models import Base, RiskRule, RiskEvent, Observation, AgentGoal, AgentRunTrace, MemberAgent, Task, DoctorReview
from executive_health_ai.models.base import utc_now
from executive_health_ai.services.management_workflow import ManagementWorkflowService
from executive_health_ai.services.health_events import ingest_health_event
from executive_health_ai.services.operational_worklist import OperationalWorklistService
from executive_health_ai.agent.supervisor import HealthOpsAgentSupervisor
from executive_health_ai.agent.tools import AgentToolRegistry
from executive_health_ai.services.autonomy import AutonomyPolicy, AutonomyGate, evaluate


@pytest.fixture
def db():
    engine = create_engine('sqlite://')
    Base.metadata.create_all(engine)
    with Session(engine, expire_on_commit=False) as session:
        p = ManagementWorkflowService().enroll(session, name='synthetic 自主管理验收',
            start=date.today(), end=date.today()+timedelta(days=364), owner='责任健管', goal='合成规则验证')
        from executive_health_ai.models.management_workflow import IntakeAssessment
        # Scenario starts after onboarding. Do not count the unrelated new-member
        # questionnaire as work generated by a risk event.
        for row in session.scalars(select(IntakeAssessment).where(IntakeAssessment.patient_id == p.patient_id)):
            row.status = 'CONFIRMED'
        session.commit()
        yield session, p
    engine.dispose()


def rule(session, level, route='HEALTH_MANAGER'):
    row = RiskRule(name='合成测试规则，非临床阈值', code='SYNTHETIC_'+str(uuid4()), applicable_device_class='ANY',
        canonical_code='steps', risk_level=level, condition_type='SYNTHETIC_TEST_THRESHOLD',
        threshold_config={'metric':'steps', 'operator':'>=', 'value':'8000', 'unit':'count'},
        window_config={}, action_type='SYNTHETIC_TEST_ONLY', source_reference='非临床合成验收依据',
        review_status='APPROVED', reviewed_by='测试规则审核人', recommended_route=route, version='test-1')
    session.add(row); session.flush()
    return row


def change(session, p, level, route='HEALTH_MANAGER', supervisor=None):
    rule(session, level, route)
    obs = Observation(patient_id=p.patient_id, observed_at=utc_now(), metric_code='steps',
        value_numeric=9000, unit='count', source='DEVICE', quality_flag='valid')
    session.add(obs); session.flush()
    event, _ = ingest_health_event(session, member_id=p.patient_id, event_type='MEANINGFUL_CHANGE',
        event_category='MEANINGFUL_CHANGE', source_type='SYSTEM', source_id=str(uuid4()),
        payload_ref={'observation_ids':[str(obs.id)], 'llm_risk':'GREEN', 'confidence':1}, supervisor=supervisor)
    session.flush()
    goal = session.get(AgentGoal, event.goal_id)
    return event, goal


def human(session, p):
    return [i for i in OperationalWorklistService().list_items(session, utc_now()) if i.member_id == p.patient_id]


@pytest.mark.parametrize('level,mode',[('GREEN','OUT_OF_LOOP'),('YELLOW','ON_THE_LOOP'),('RED','IN_THE_LOOP')])
def test_risk_mode_and_safe_read(level, mode):
    tool=AgentToolRegistry().get('get_health_record')
    d=AutonomyPolicy().decide(risk_level=level,goal_type='DAILY_CARE',tool=tool)
    assert d.autonomy_mode==mode and not d.requires_human


@pytest.mark.parametrize('level',['GREEN','YELLOW','RED'])
def test_tool_permission_cannot_be_weakened(level):
    r=AgentToolRegistry(); p=AutonomyPolicy()
    assert p.decide(risk_level=level,goal_type='DAILY_CARE',tool=r.get('start_next_phase')).decision=='REQUIRE_MANAGER'
    assert p.decide(risk_level=level,goal_type='DAILY_CARE',tool=replace(r.get('get_health_record'),autonomy_level='FORBIDDEN')).decision=='BLOCK'


def test_green_automatic_closure_no_human_work(db):
    s,p=db; event,goal=change(s,p,'GREEN')
    assert goal.status=='COMPLETED', goal.context_json
    assert human(s,p)==[]
    assert s.scalar(select(AgentRunTrace).where(AgentRunTrace.goal_id==goal.id,AgentRunTrace.action=='autonomy_decision'))
    assert s.scalar(select(MemberAgent).where(MemberAgent.member_id==p.patient_id)) is not None
    from executive_health_ai.models import AgentPlanStep
    gate=s.scalar(select(AgentPlanStep).where(AgentPlanStep.plan_id==goal.current_plan_id,AgentPlanStep.requires_approval.is_(True)))
    assert gate.status=='SKIPPED' # Never invent a manager approval.


def test_yellow_prepares_before_single_human_gate(db):
    s,p=db; _,goal=change(s,p,'YELLOW')
    assert goal.status=='WAITING_MANAGER', goal.context_json
    assert goal.context_json['preparation_complete']
    assert len(human(s,p))==1
    assert s.scalar(select(func.count(Task.id)))==0
    assert '联系会员' in goal.next_action


def test_red_doctor_route_same_goal_resume_no_downgrade(db):
    s,p=db; event,goal=change(s,p,'RED','DOCTOR')
    assert goal.status=='WAITING_DOCTOR', goal.context_json
    reviews=list(s.scalars(select(DoctorReview)))
    assert len(reviews)==1 and human(s,p)[0].priority==0
    assert human(s,p)[0].status=='等待医生'
    from executive_health_ai.services.risk_operations import RiskOperationsService
    RiskOperationsService().complete_doctor_review(s,reviews[0].id,'验收医生','全科','合成测试意见：请按计划核对','联系会员并记录结果')
    returned,_=ingest_health_event(s,member_id=p.patient_id,event_type='DOCTOR_REVIEW_COMPLETED',
        event_category='NEW_INFORMATION',source_type='SYSTEM',source_id=str(reviews[0].id))
    assert returned.goal_id==goal.id and goal.status=='WAITING_MANAGER'
    assert s.scalar(select(func.count(AgentGoal.id)))==1
    assert s.scalar(select(RiskEvent)).risk_level=='RED'
    from executive_health_ai.services.task_transitions import TaskTransitionService
    from executive_health_ai.services.risk_triage import RiskEvaluationService
    from executive_health_ai.services.daily_care import reconcile
    task=s.scalar(select(Task).where(Task.risk_event_id==reviews[0].risk_event_id))
    TaskTransitionService().complete(s,task.id,actor='责任健管',outcome='已联系并记录合成反馈')
    risk=s.get(RiskEvent,reviews[0].risk_event_id)
    RiskEvaluationService().close_manual_event(s,risk,'责任健管','已完成本次处置','医生结果与后续反馈已记录')
    reconcile(s,HealthOpsAgentSupervisor())
    assert goal.status=='COMPLETED' and risk.risk_level=='RED' and risk.status=='CLOSED'


@pytest.mark.parametrize('route',['HEALTH_MANAGER','ESCALATE'])
def test_red_not_always_doctor(db,route):
    s,p=db;_,g=change(s,p,'RED',route)
    assert g.status=='WAITING_MANAGER'
    assert s.scalar(select(func.count(DoctorReview.id)))==0
    assert human(s,p)[0].owner=='责任健管'


def test_llm_cannot_set_or_downgrade_formal_risk(db):
    s,p=db;_,g=change(s,p,'RED')
    g.context_json={**g.context_json,'risk_level':'GREEN','summary':'可能问题不大','confidence':1}
    d=evaluate(s,AgentToolRegistry().get('create_followup'),g)
    assert d.risk_level=='RED' and d.decision=='REQUIRE_MANAGER'
    assert d.risk_rule_version=='test-1'
    with pytest.raises(AutonomyGate):AgentToolRegistry().execute(s,'create_followup',g,{'risk_level':'GREEN'})
    assert s.scalar(select(RiskEvent)).risk_level=='RED'


def test_device_100_raw_zero_wake_one_change_one_evaluation(db,monkeypatch):
    s,p=db;rule(s,'YELLOW');now=utc_now()
    from executive_health_ai.services.risk_triage import RiskEvaluationService
    original=RiskEvaluationService.evaluate_observation
    evaluations=[]
    def counted(self,session,observation_id):
        evaluations.append(observation_id)
        return original(self,session,observation_id)
    monkeypatch.setattr(RiskEvaluationService,'evaluate_observation',counted)
    for n in range(100):
        ingest_health_event(s,member_id=p.patient_id,event_type='DEVICE_RAW_MEASUREMENT',event_category='NEW_INFORMATION',
            source_type='DEVICE',source_id=str(n),payload_ref={'measurement':{'metric':'steps','value':9000,'unit':'count','observed_at':now.isoformat()}})
    agent=s.scalar(select(MemberAgent).where(MemberAgent.member_id==p.patient_id))
    assert agent.wake_count==0 and s.scalar(select(func.count(Observation.id)))==100
    assert evaluations==[]
    from executive_health_ai.services.health_event_measurements import evaluate_window
    kwargs=dict(member_id=p.patient_id,metric='steps',threshold=8000,minimum_count=3,
        window_start=now-timedelta(days=1),window_end=now+timedelta(seconds=1),rule_id='synthetic-window')
    event=evaluate_window(s,**kwargs);same=evaluate_window(s,**kwargs)
    assert same.id==event.id and agent.wake_count==1
    assert event.payload_ref['risk_evaluation']['engine']=='deterministic'
    assert len(evaluations)==1
    assert s.scalar(select(func.count(AgentGoal.id)))==1 and len(human(s,p))==1


def test_failed_green_retries_bounded_and_escalates(db,monkeypatch):
    s,p=db;supervisor=HealthOpsAgentSupervisor();supervisor.default_max_retries=1
    original=supervisor.registry.execute
    def broken(session,name,*args,**kwargs):
        if name=='get_current_phase':raise RuntimeError('synthetic failure')
        return original(session,name,*args,**kwargs)
    monkeypatch.setattr(supervisor.registry,'execute',broken)
    _,g=change(s,p,'GREEN',supervisor=supervisor)
    assert g.status=='RUNNING' and g.next_check_at
    from executive_health_ai.services.daily_care import advance
    g.next_check_at=utc_now()-timedelta(seconds=1);advance(s,g,supervisor)
    assert g.status=='WAITING_MANAGER'
    assert len(human(s,p))==1
    advance(s,g,supervisor)
    assert s.scalar(select(func.count(Task.id)))==1


def test_authorized_close_resumes_same_goal(db):
    s,p=db;_,g=change(s,p,'YELLOW')
    from executive_health_ai.services.risk_operations import RiskOperationsService
    from executive_health_ai.services.daily_care import reconcile
    risk=s.scalar(select(RiskEvent))
    RiskOperationsService().close(s,risk.id,'责任健管','核对会员反馈和来源资料，确定无需继续跟进')
    reconcile(s,HealthOpsAgentSupervisor())
    assert g.status=='COMPLETED' and human(s,p)==[]


def test_unknown_risk_is_not_green(db):
    s,p=db
    from executive_health_ai.services.autonomy import current_risk
    assert current_risk(s,p.patient_id) is None


def test_yellow_automatic_preparation_not_yet_human_work(db,monkeypatch):
    s,p=db; supervisor=HealthOpsAgentSupervisor()
    monkeypatch.setattr(supervisor.registry,'execute',lambda *a,**k: (_ for _ in ()).throw(RuntimeError('暂不可用')))
    _,g=change(s,p,'YELLOW',supervisor=supervisor)
    assert g.status=='RUNNING' and human(s,p)==[]


def test_yellow_safe_write_and_red_blocked_write():
    p=AutonomyPolicy();tool=AgentToolRegistry().get('write_management_log')
    assert p.decide(risk_level='YELLOW',goal_type='DAILY_CARE',tool=tool).decision=='AUTO_WITH_OVERSIGHT'
    assert p.decide(risk_level='RED',goal_type='DAILY_CARE',tool=tool).decision=='REQUIRE_MANAGER'


def test_decision_and_rule_version_survive_session_restart(db):
    s,p=db;_,g=change(s,p,'RED','DOCTOR');identity=g.id;engine=s.bind;s.commit()
    with Session(engine) as resumed:
        goal=resumed.get(AgentGoal,identity)
        assert goal.status=='WAITING_DOCTOR'
        decisions=list(resumed.scalars(select(AgentRunTrace).where(AgentRunTrace.goal_id==identity,
            AgentRunTrace.action=='autonomy_decision')))
        assert decisions and all(d.metadata_json['policy_version']=='autonomy-1' for d in decisions)
        assert all(d.metadata_json['risk_rule_version']=='test-1' for d in decisions)


def test_red_priority_even_when_waiting_doctor(db):
    from executive_health_ai.ui.experience import sorted_work
    from executive_health_ai.services.operational_worklist import OperationalWorkItem
    s,p=db;_,g=change(s,p,'RED','DOCTOR')
    red=human(s,p)[0]
    yellow=replace(red,source_id=uuid4(),priority=1,status='待处理',due_at=utc_now()-timedelta(days=1))
    assert sorted_work([yellow,red],utc_now())[0] is red


def test_green_followup_requires_real_approved_plan():
    p=AutonomyPolicy();tool=AgentToolRegistry().get('create_followup')
    assert p.decide(risk_level='GREEN',goal_type='DAILY_CARE',tool=tool).decision=='REQUIRE_MANAGER'
    assert p.decide(risk_level='GREEN',goal_type='DAILY_CARE',tool=tool,
        member_context={'approved_operational_plan':True}).decision=='AUTO_EXECUTE'


def test_missing_annual_plan_does_not_suppress_red(db):
    from executive_health_ai.models import Patient
    from types import SimpleNamespace
    s,_=db
    member=Patient(external_id='synthetic-without-plan',display_name='合成待建方案会员',timezone='Asia/Tokyo')
    s.add(member);s.flush()
    _,g=change(s,SimpleNamespace(patient_id=member.id),'RED','DOCTOR')
    assert g.status=='WAITING_DOCTOR'
    assert g.context_json['program_id'] is None


def test_ingestion_cannot_forge_risk_evaluation_receipt(db):
    s,p=db
    with pytest.raises(ValueError,match='只能由确定性'):
        ingest_health_event(s,member_id=p.patient_id,event_type='MEANINGFUL_CHANGE',event_category='MEANINGFUL_CHANGE',
            source_type='SYSTEM',source_id='forged',payload_ref={'risk_evaluation':{'risk_level':'GREEN'}})
    assert s.scalar(select(MemberAgent).where(MemberAgent.member_id==p.patient_id)).wake_count==0


def test_durable_tool_approval_resumes_its_own_step(db):
    from executive_health_ai.models import AgentPlan, AgentPlanStep, AgentApprovalRequest
    from executive_health_ai.agent.tools import AgentTool, AUTO
    s,p=db;supervisor=HealthOpsAgentSupervisor();_,g=change(s,p,'YELLOW',supervisor=supervisor)
    calls=[]
    supervisor.registry.register(AgentTool('test_operational_arrangement','合成权限验收',AUTO,'write',True,10,
        lambda *_: calls.append('executed') or {'prepared':True}))
    plan=s.get(AgentPlan,g.current_plan_id)
    step=s.scalar(select(AgentPlanStep).where(AgentPlanStep.plan_id==plan.id).order_by(AgentPlanStep.step_order))
    step.status,step.tool_name='PENDING','test_operational_arrangement'
    assert not supervisor._run_tool(s,g,plan,step,event_id=None)
    assert not calls and step.retry_count==0
    approval=s.scalar(select(AgentApprovalRequest).where(AgentApprovalRequest.plan_step_id==step.id))
    supervisor.decide_approval(s,approval.id,decision='APPROVED',actor='责任健管',actor_role='HEALTH_MANAGER')
    assert calls==['executed'] and step.status=='COMPLETED'


def test_old_doctor_result_cannot_clear_new_red(db):
    s,p=db;_,old=change(s,p,'YELLOW','DOCTOR')
    from uuid import UUID
    from executive_health_ai.services.risk_operations import RiskOperationsService
    old_review=s.get(DoctorReview,UUID(old.context_json['review_id']))
    RiskOperationsService().complete_doctor_review(s,old_review.id,'验收医生','全科','旧事项已判断','按旧意见核对')
    _,new=change(s,p,'RED','DOCTOR')
    ingest_health_event(s,member_id=p.patient_id,event_type='DOCTOR_REVIEW_COMPLETED',
        event_category='NEW_INFORMATION',source_type='SYSTEM',source_id=str(old_review.id))
    assert old.status=='WAITING_MANAGER' and new.status=='WAITING_DOCTOR'
    assert old.context_json['review_id']==str(old_review.id)
    assert old.context_json['review_id']!=new.context_json['review_id']
    assert s.get(DoctorReview,UUID(new.context_json['review_id'])).status=='PENDING'


def test_existing_yellow_management_result_still_completes(db):
    from executive_health_ai.services.risk_operations import RiskOperationsService
    from executive_health_ai.services.task_transitions import TaskTransitionService
    s,p=db;change(s,p,'YELLOW');risk=s.scalar(select(RiskEvent))
    row=RiskOperationsService().adjust_management(s,risk.id,'责任健管','核对合成会员作息','会员已有反馈')
    TaskTransitionService().complete(s,row.id,actor='责任健管',outcome='已记录管理反馈')
    assert row.status=='COMPLETED' and risk.status=='IN_REVIEW'


def test_green_due_approved_system_check_not_human_contact(db):
    from executive_health_ai.models import HealthProblem, ManagementPlan
    s,p=db;change(s,p,'GREEN')
    problem=HealthProblem(patient_id=p.patient_id,program_id=p.id,title='合成管理目标',
        description='非医学计划核对',severity='LOW',responsible_role='health_manager',source='synthetic')
    s.add(problem);s.flush()
    plan=ManagementPlan(patient_id=p.patient_id,program_id=p.id,health_problem_id=problem.id,
        title='已批准随访计划',content='系统核对安排；实际联系仍由健管完成',source='synthetic',
        status='ACTIVE',owner=p.owner,start_date=date.today(),adjusted_by=p.owner,adjusted_at=utc_now())
    s.add(plan);s.flush()
    check=Task(patient_id=p.patient_id,program_id=p.id,management_plan_id=plan.id,title='核对计划到期安排',
        instruction='只核对已有计划',responsible_role='system',source='approved_plan_check',due_at=utc_now())
    s.add(check);s.flush()
    event,_=ingest_health_event(s,member_id=p.patient_id,event_type='TIME_DUE',event_category='TIME_DUE',
        source_type='SYSTEM',source_id='system-check:'+str(check.id),occurred_at=utc_now(),
        payload_ref={'work_kind':'task','work_id':str(check.id)})
    goal=s.get(AgentGoal,event.goal_id)
    assert goal.status=='COMPLETED' and check.status=='COMPLETED'
    assert human(s,p)==[]
    # Normal member contact remains a real human responsibility even at GREEN.
    contact=Task(patient_id=p.patient_id,program_id=p.id,management_plan_id=plan.id,title='电话联系会员',
        instruction='记录真实反馈',responsible_role='health_manager',source='approved_followup',due_at=utc_now())
    s.add(contact);s.flush()
    assert len(human(s,p))==1
