"""Add risk rule, event and emergency-contact foundation.

Revision ID: 0009_add_risk_triage_engine
Revises: 0008_add_knowledge_base_foundation
"""
from alembic import op
import sqlalchemy as sa
revision="0009_add_risk_triage_engine"; down_revision="0008_add_knowledge_base_foundation"; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("risk_rules",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("name",sa.String(200),nullable=False),sa.Column("code",sa.String(100),nullable=False),sa.Column("applicable_device_class",sa.String(32),nullable=False),sa.Column("canonical_code",sa.String(100)),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("condition_type",sa.String(64),nullable=False),sa.Column("threshold_config",sa.JSON(),nullable=False),sa.Column("window_config",sa.JSON(),nullable=False),sa.Column("requires_repeated_measurement",sa.Boolean(),nullable=False),sa.Column("requires_symptom_confirmation",sa.Boolean(),nullable=False),sa.Column("action_type",sa.String(64),nullable=False),sa.Column("source_reference",sa.Text(),nullable=False),sa.Column("version",sa.String(64),nullable=False),sa.Column("review_status",sa.String(32),nullable=False),sa.Column("reviewed_by",sa.String(128)),sa.Column("reviewed_at",sa.DateTime(timezone=True)),sa.Column("is_active",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("code"))
    op.create_table("risk_events",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("patient_id",sa.Uuid(),sa.ForeignKey("patients.id"),nullable=False),sa.Column("risk_rule_id",sa.Uuid(),sa.ForeignKey("risk_rules.id"),nullable=False),sa.Column("risk_level",sa.String(16),nullable=False),sa.Column("status",sa.String(32),nullable=False),sa.Column("device_class",sa.String(32),nullable=False),sa.Column("canonical_code",sa.String(100)),sa.Column("evidence_json",sa.JSON(),nullable=False),sa.Column("summary",sa.Text(),nullable=False),sa.Column("requires_manager_review",sa.Boolean(),nullable=False),sa.Column("requires_doctor_review",sa.Boolean(),nullable=False),sa.Column("requires_emergency_action",sa.Boolean(),nullable=False),sa.Column("acknowledged_by",sa.String(128)),sa.Column("acknowledged_at",sa.DateTime(timezone=True)),sa.Column("resolved_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_table("emergency_contacts",sa.Column("id",sa.Uuid(),primary_key=True),sa.Column("patient_id",sa.Uuid(),sa.ForeignKey("patients.id"),nullable=False),sa.Column("name",sa.String(128),nullable=False),sa.Column("relationship",sa.String(64),nullable=False),sa.Column("phone",sa.String(64),nullable=False),sa.Column("is_primary",sa.Boolean(),nullable=False),sa.Column("consent_status",sa.String(32),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
def downgrade(): op.drop_table("emergency_contacts"); op.drop_table("risk_events"); op.drop_table("risk_rules")
