"""Business event vocabulary used to wake durable HealthOps goals."""

EVENT_TYPES = frozenset({
    "REPORT_UPLOADED", "REPORT_CONFIRMED", "BASELINE_CONFIRMED",
    "NEW_OBSERVATION", "RISK_CREATED", "RISK_UPDATED", "TASK_COMPLETED",
    "TASK_OVERDUE", "DOCTOR_REVIEW_COMPLETED", "SERVICE_COMPLETED",
    "OUTCOME_RECORDED", "REVIEW_DUE", "DATA_STALE",
})

GOAL_START_EVENTS = {"REPORT_UPLOADED": "POST_CHECKUP_MANAGEMENT"}

WAIT_EVENT_STATUSES = {
    "REPORT_CONFIRMED": "WAITING_MANAGER",
    "RISK_CREATED": "WAITING_MANAGER",
    "DOCTOR_REVIEW_COMPLETED": "WAITING_DOCTOR",
    "REVIEW_DUE": "WAITING_TIME",
    "OUTCOME_RECORDED": "WAITING_EVENT",
}
